all:
	echo Running p1-082674-148131
	python3.6 src/convolution_tests.py
	python3.6 src/convolution_borders.py
	python3.6 src/gp_test.py
	python3.6 src/lp_test.py
	python3.6 src/pb_test.py 
	python3.6 src/teste_dft.py
